FROM node:6

RUN apt-get update &&  apt-get install git

ADD package.json kubeless_rt/
ADD lib/helper.js kubeless_rt/lib/
ADD kubeless.js kubeless_rt/

WORKDIR kubeless_rt/

RUN npm install

USER 1000

CMD ["node", "kubeless.js"]
