FROM node:6-alpine

ARG TARGET=http-trigger
RUN apk add --no-cache git

ADD ${TARGET}/package.json /

RUN npm install

ADD lib/helper.js /lib/
ADD ${TARGET}/kubeless.js /

CMD ["node", "/kubeless.js"]
