FROM node:8

ARG TARGET=http-trigger
RUN apt-get update &&  apt-get install git

ADD lib/helper.js /lib/
ADD ${TARGET}/kubeless.js /
ADD ${TARGET}/package.json /

RUN npm install

CMD ["node", "/kubeless.js"]
