---
apiVersion: k8s.io/v1
kind: Function
metadata:
  name: function1
spec:
  handler: hello.foobar
  runtime: nodejs2.7
  function: |
      module.exports = {
        foo: function (req, res) {
          console.log(req.body)
          res.end('hello world')
        }
      }
