FROM microsoft/aspnetcore-build:2.0.0

WORKDIR /app

RUN dotnet new library -n project -o .

RUN dotnet add package Kubeless.Functions

RUN mv /root/.dotnet /root/.nuget /

RUN chown 1000 /.dotnet/ /.nuget/