#!/usr/bin/env bash

# Copyright (c) 2016-2017 Bitnami
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -e


GIT_COMMIT=$(git describe --tags --dirty)
BUILD_FLAGS=(-ldflags="-w -X github.com/kubeless/kubeless/pkg/version.Version=${GIT_COMMIT}")

# Get rid of existing binary
echo "Removing Old Kubeless binaries"
rm -f ${GOPATH%%:*}/bin/kubeless
rm -f ${GOPATH%%:*}/bin/function-controller

echo "Build Kubeless Components binaries"
# Build binary
go install \
    "${BUILD_FLAGS[@]}" \
    github.com/kubeless/kubeless/cmd/...

if [ $? -eq 0 ]; then
  echo "Build Kubeless Components successful. Program saved at ${GOPATH%%:*}/bin"
else
  echo "Build Kubeless Components failed."
fi
